-- CreateEnum
CREATE TYPE "BrideStage" AS ENUM ('CONSULTATION', 'FIRST_FITTING', 'SECOND_FITTING', 'THIRD_FITTING', 'FINAL_FITTING', 'ALTERATION', 'COLLECTION_READY');

-- AlterTable
ALTER TABLE "bride_profiles" ADD COLUMN     "stage" "BrideStage" NOT NULL DEFAULT 'CONSULTATION';
